const LazyLoading = () => {
    return(
        <div>
            Family is the place where you learn your first lesson in life. Your family members are the only assets that will remain with you forever. Whatever the circumstances, family members are always there for each other to support us. Good values and good morals are always taught in a family.
            In the family, we are prepared to respect our elders and love younger ones. We learn lessons consistently from our family, about honesty, dependability, kindness and so on. Although I am a student in my final year, my family always treats me like a child but always provides me with a sensation of so much love and care.
            My family is the best family for me. I live in a nuclear family of five members. My father is a teacher. He is the man who heads and leads our family. He brings the family into reality. My father is my hero as he predicts the need of the time and raises his family by bearing all the responsibilities and discharging all the duties for giving a required shape. I respect him for his great deeds.
            My father does not force me to go for a career his choice. He does not want that his son should follow only his profession. He wants that his son should go according to his own choice, suitability, and capability. But my father desires his son should go for a better future.
            My mother is a housewife as well as a beautician. She is a lovely woman. My mother is everything to me. She is the one who understands me best and most closely. My mother is my co-partner in everyday work and different issues.
            My mother was the most beautiful woman I have ever seen. She is my mother, who shapes me, to become a nobleman through her great, insightful, and elegant activities. My mother motivates me to learn by consenting to the activities which are important for character building and improvement. My mother creates an environment for me to learn enough in a natural manner.
            My grandmother is the cutest person of all. In light of her, everybody has to get up early in the morning. She is fond of making sweet dishes and we love what she does. She is a focused woman and because of her everything needs to be in order.
            My brother, who is elder than me, is the tallest. He is a Youtuber and is fond of cooking. He loves to play cricket and is a gadget freak. He doesn’t study much but is very sweet and gentlemanly.
            I love my family because they are the jewels of my life. They work hard so that we can get anything we desire makes me love and respect my parents considerably more. We play games every night and discuss various topics to spend some quality time together.
            I give deep respect and pay the highest regard to my family not just because they are my family, but for their unmatched and incredible sacrifices for me.0A diet that contains all kinds of necessary ingredients in almost the required quantity is called the “Balanced Diet”. A Balanced diet is one that helps to maintain or improve overall health. We should consume a balanced diet consisting of essential nutrition: liquids, adequate proteins, essential fatty acids, vitamins, minerals, and calories. We must eat fresh fruits, salad, green leafy vegetables, milk, egg, yoghurt, etc. on time in order to maintain a healthy body.
            My father is the man who heads and leads our family. He brings the family into reality. But in a real sense, my father predicts the need of the time and raises his family by bearing all the responsibilities and discharging all the duties for giving a required shape. I respect him for his great deeds.
            My father is financially weak but fulfils my genuine requirements and guarantees that I should not be a survivor of feelings of inadequacy. My poor father does not hesitate to sweat heavily to enhance his earnings for my sake. He eats a little less but does not think twice about taking care of mine.
            My father does not force me to go for a career of my papa’s choice. He does not want that his son should follow only his profession. He wants that his son should go according to his own choice, suitability, and capability. The tradition of specific jobs running in the family is literally dying. A doctor is not wanting his son to be a doctor, a professor is avoiding his profession for his children, an army officer is not forcing his son to join the defence forces, and so on. But my father desires his son should go for a better future. Among the minerals, we require chiefly iron, calcium, sodium, potassium, and small quantities of iodine, copper, etc. They are found in green vegetables and most fruits, Vitamins have a number of kinds like A, B, C, D, etc. Vitamin A is found in fish oil, butter, carrot, papaya, etc., and Vitamin B is found in green leafy vegetables, wheat grain, etc. Vitamin C is found in green chilli, green vegetables, amla, lemon, and citric fruits. Vitamin D is found in the first oil, butter, and rays of the sun. We also need Vitamins E and K for our health. Milk is perhaps the only single item that can be called a balanced diet in itself.
            My Father is a mature and agreeable individual who assists me make important decisions. Like most doting fathers, he plays a very important role in my life helping me build my career as well as resolve my everyday issues too. When I am looking for help and guidance against the odds, I, first of all, approached my father who comes forward leaving all his personal priorities and doing the needful. My father is a person who works tirelessly and makes countless penances to figure out my issues.My father goes with me in all the activities ensuring my correct moves. He really looks at my problem and moulds me by giving lectures in the series in order to form a lovely sense in my mind. His concern is for my better career. My father is mature enough, knowledgeable, and very much aware of my cutting-edge needs, evaluates my inclination as well as decision, and does all-out efforts to develop me for accomplishing my objective.
            My father is educated and has a logical vision. Today, my father has transformed into a trendy dad. His thinking is new which suits the time. He takes full advantage of his knowledge and modernization in raising me suitably and making me capable and confident to confront the competitive life that is prevailing today. Animal protein is found in meats, poultry, and fish. The white of an egg also contains protein. Another kind of protein is found in milk (casein), cheese, curd, pulses, soybean, dry fruits, etc. Fat is found in butter, pork, coconut, all edible oils, cod liver oil, the yolk of an egg, etc.
            My father as an ideal father makes all efforts to meet my necessities. He would rather not leave any lacuna which may affect my development and career-building process. We should eat only fresh, well-washed and well-cooked food articles which are free from dust and flies. Fried foods and foods containing excess fat, spices, and chillis are harmful. Roadside eating should be avoided. We should take the last meal two or three hours before going to bed. There should be a good time gap between two meals so that the food gets digested in our stomachs.
            We celebrate Father’s Day every year on 19 June to strengthen the relationship and remind a father of the sacrifices he endured towards his kids when they were in need.A healthy body also needs some daily physical activities, proper rest and sleep neatness, a healthy environment, fresh air, and water, personal hygiene, etc. Also, we should drink more water at least 7-8 glasses of water. It balances blood pressure and supplies vital nutrients exceptionally quickly to the body. A fit and healthy individual turns out to be more resistant to infections and diseases.
            It is very important that we should give deep respect and pay the highest regard to our fathers. Wealth matters, but, is not as important as health. Spending lots of money on junk food in five-star hotels or on other entertainment sources like watching films for a day and so on has no advantages other than self-satisfaction. Being physically and mentally healthy helps an individual to be socially and financially healthy as well.
            The moment a child is born, the mother is born as well. When a child gets a sense, it looks up at its mother and starts to follow the mother’s movements. The mind of a child is generally very sharp. It copies the activities of the mother eagerly. Mother takes all the care of her kid from all points like health, dress, diet, entertainment, education, sports, and development of competitive aptitude. The mother attracts the kid through love and affection.
            We can describe motherhood in terms of sacrifice. My mother ignores her comforts and works hard for good food, wear, and education for me. It is a natural and noteworthy quality that is wholly found in a mother. My mother bears the responsibility of motherhood not only from a young age, but she remains a trusted adviser throughout my life. It is very important that we should give deep respect and pay the highest regard to our mothers not just because they are mothers, but for their unmatched motherhood and incredible sacrifices towards us.
            My mother is everything to me. She is the one who understands me best and most closely. My mother is my co-partner in everyday work and different issues. Sometimes my mother takes on a tremendous amount of responsibility and works under tension, when I need her, to take up its battle, both personally and professionally, to accomplish the troublesome objective in my work or business. We should owe our mothers for their everything.
            There is an extraordinary job the mother does in influencing the kid. The foundation made by my mother through affection, persistence, discipline, direction, and tears permits me to cruise upon my ocean. It is my mother, who shapes me, to become a nobleman through her great, insightful, and elegant activities. My mother motivates me to learn by consenting to the activities which are important for character building and improvement. My mother creates an environment for me to learn enough in a natural manner.
            Sometimes my mother uses specific hard measures to discipline me and teach me valuable lessons. She denounces me by denying me food. She forbids me to indulge in undesirable activities. Sometimes, she makes the dreaded beating with the rod. She shows her dismay. She warns of the carefulness. But I know, she is very soft from the inside. She is a well-wisher of mine. Her only point is that she needs her child free from inadequacies.
            There are some cases when the children especially the individuals who are not depending on their parents and are working away, have forgotten their mothers. They don’t go home for quite a long time but their mothers still pray with all their hearts that they stay blissful and happy. She will ever remain a well-wisher of her children regardless of the circumstances.
            It is very important that we should give deep respect and pay the highest regard to our mothers not just because they are mothers, but for their unmatched motherhood and incredible sacrifices towards us.
            People eat junk foods and other unhealthy food items only for taste. They don’t even have time to nourish their bodies with the required diet. A healthy and balanced diet reduces stress and promotes healthy life without suffering. Thus, it stands out of utmost importance to individuals to examine the significance of a healthy body.
        </div>
    )
}

export default LazyLoading